### ISSUE TITLE
fast meters start reading before pattern is stabilized

### ISSUE THREAD

**Issue by badchill** [scyomantion/FakeSensor#2]
Using a Klein K-10 and JVC RS500, and having color and gamma 33 point calibration selected in the JVC software, the probe starts reading the first red 33 point gamma measurement before the pattern has finished rendering in the projector. This usually results in the first red measurement having a higher luminance than the second (for instance first measurement .3 nits, second .02 nits, third .1, and ascending from there), often resulting in terrible grayscale tracking at the dark end. The first measurement should be the lowest reading. There may be other levels in the range that are being effected, as there also was a suspicious spike in the gamma and grayscale tracking farther up the brightness range.

The Klein is connected with a USB to serial adapter.

**Comment by scyomantion** [comment]
sounds like a problem in the JVC software, that it trust in the delay of the spyder sensor but the Klein K-10 is to fast with dark readings. I would suggest that I add a delay config option, so that readings could be delayed by a specified time.

**Comment by scyomantion** [comment]
please try to increase the new delay setting in autocal.ini
The value is in seconds
